---
- name: "Install software-properties-common"
  package:
    pkg: "{{ install_software_properties_common_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  tags:
    - "software-properties-common"
